/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example.sample;

import java.time.LocalDate;
import java.util.Arrays;

import lombok.val;

public class App {

    private static void write1() {
        val headers = new String[] { "id", "name", "gender", "birthDate" };
        val rows = Arrays.asList(
                new Object[][] {
                        { 1, "ボブ", "male", LocalDate.of(1979, 3, 23) },
                        { 2, "sala", "female", LocalDate.of(1984, 8, 18) },
                        { 3, "李華", LocalDate.of(1987, 1, 8) },
                        { 4, "山田花子", "", LocalDate.of(1985, 11, 30) },
                });
        CsvSample.writeHeadersAndRows(headers, rows);
        TsvSample.writeHeadersAndRows(headers, rows);
    }

    public static void main(String[] args) {
        write1();
    }
}
